name: Check formatting

on:
  pull_request:
  push:
    branches:
      - master

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  format:
    strategy:
      matrix:
        solution:
          - AspNetCore
          - AspNetCoreController
          - AspNetCoreCustom
          - AspNetCoreMulti
          - AspNetWebApi
          - AzureFunctions
          - ClientNet462
          - StarWars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          source-url: https://nuget.pkg.github.com/graphql-dotnet/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        working-directory: src/${{ matrix.solution }}
        run: dotnet restore
      - name: Check formatting
        working-directory: src/${{ matrix.solution }}
        run: |
          dotnet format --no-restore --verify-no-changes --severity error || (echo "Run 'dotnet format' to fix issues" && exit 1)
